### ISSUE TITLE
Inquire - revise the HoloLens Curved Keyboard app  

### ISSUE THREAD

**Issue by hejibo** [JannikLassahn/hololens-curvedkeyboard#1]
Hello Jannik, 

This is Dr. Jibo He from Wichita State University.  My group hopes to do a research project using your code. WE hope to revise your code. We need to manipulate the curvature of the curved keyboard, the size of each key and the relative location of the keyboard, and add a log file on the time and key button name when a key is logged. 

Can you give me an estimate how much you hope to get for this work? We can offer you either cash or authorship for your work. Let me know if you need additional information. My email is jibo.he@wichita.edu. Thanks.  

Jibo

https://github.com/JannikLassahn/hololens-curvedkeyboard

**Comment by JannikLassahn** [comment]
This project is using the [Unlicense](https://github.com/JannikLassahn/hololens-curvedkeyboard/blob/master/LICENSE). You can use and modify the code however you want to.
I wish you all the best for your research project.
